import * as BABYLON from '@babylonjs/core';

//filtering happens here
export const FILTER_GROUP_PLAYER = 1;
export const FILTER_GROUP_GROUND = 2;
export const FILTER_GROUP_WALL = 4;
export const FILTER_GROUP_PLAYER_MP = 8;

export const FILTER_MASK_PLAYER_NO_COLLISSIONS = FILTER_GROUP_GROUND | FILTER_GROUP_WALL;
export const FILTER_MASK_PLAYER_WITH_COLLISSIONS = FILTER_GROUP_GROUND | FILTER_GROUP_WALL | FILTER_GROUP_PLAYER_MP;

export const FILTER_MASK_PLAYER_MP_NO_COLLISSIONS = FILTER_GROUP_GROUND | FILTER_GROUP_WALL;
export const FILTER_MASK_PLAYER_MP_WITH_COLLISSIONS = FILTER_GROUP_GROUND | FILTER_GROUP_WALL | FILTER_GROUP_PLAYER;